### ISSUE TITLE
Issues with LibXML::HashMap

### ISSUE THREAD

**Issue by dwarring** [p6-xml/LibXML-p6#12]
I'm having problems getting LibXML::HashMap working as below:
```
prove -e'perl6 -I .' -v t/00hash-object.t 
t/00hash-object.t .. 
1..2
    1..4
    ok 1 - keys
    ok 2 - values
    ok 3 - # SKIP hash updates
    ok 4 - # SKIP hash updates
Type check failed for return value; expected NativeCall::Types::Pointer but got Whatever (*)
  in method Lookup at /home/david/git/LibXML-p6/lib/LibXML/Native/HashTable.pm6 (LibXML::Native::HashTable) line 11
  in method EXISTS-KEY at /home/david/git/LibXML-p6/lib/LibXML/HashMap.pm6 (LibXML::HashMap) line 172
  in block <unit> at t/00hash-object.t line 23

Dubious, test returned 1 (wstat 256, 0x100)
Failed 2/2 subtests 

Test Summary Report
-------------------
t/00hash-object.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
Files=1, Tests=0,  2 wallclock secs ( 0.03 usr  0.00 sys +  2.30 cusr  0.13 csys =  2.46 CPU)
Result: FAIL
```

Skipping theses tests for now. May have an impact in LibXML::SAX::Builder, which uses them for attributes processing.

**Comment by dwarring** [comment]
I think LibXML::SAX::Builder, is ok, because its only using  a simple string and its tests + 00hash-simple.t are passing.

**Comment by markldevine** [comment]
David,

I was able to build your latest LibXML-p6.

Alienware Area-51 R4
Windows 10 Pro
Hyper-V Virtual Machine
Linux services 4.14.35-1902.4.8.el7uek.x86_64 #2 SMP Sun Aug 4 22:25:18 GMT 2019 x86_64 x86_64 x86_64 GNU/Linux

This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.

/usr/bin/wc ManagedSystem.xml
  53199  139417 4184164 ManagedSystem.xml

exemel<https://github.com/supernovus/exemel>
for ((i=1; i<=3; i++)); do perl6 -M XML -e 'my $start = now; $ = from-xml(slurp("ManagedSystem.xml")); note "parse: " ~ now - $start;'; done
parse: 11.698402811
parse: 12.140521
parse: 13.0865156

LibXML-p6<https://github.com/p6-xml/LibXML-p6>
for ((i=1; i<=3; i++)); do perl6 -M LibXML -e 'my $xml-manager = LibXML.new; my $start = now; $ = $xml-manager.parse(:string(slurp("ManagementConsole.xml"))); note "parse: " ~ now - $start;'; done
parse: 0.0128505
parse: 0.01328376
parse: 0.0123331

Awesome!

Thanks for working on this,

Mark

**Comment by markldevine** [comment]
Sorry wrong comparison.  Emended below…


From: Mark Devine
Sent: Tuesday, August 20, 2019 18:59
To: p6-xml/LibXML-p6 <reply@reply.github.com>
Subject: RE: [p6-xml/LibXML-p6] Issues with LibXML::HashMap (#12)

David,

I was able to build your latest LibXML-p6.

Alienware Area-51 R4
Windows 10 Pro
Hyper-V Virtual Machine
Linux services 4.14.35-1902.4.8.el7uek.x86_64 #2 SMP Sun Aug 4 22:25:18 GMT 2019 x86_64 x86_64 x86_64 GNU/Linux

This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.

/usr/bin/wc ManagedSystem.xml
  53199  139417 4184164 ManagedSystem.xml

exemel<https://github.com/supernovus/exemel>
for ((i=1; i<=3; i++)); do perl6 -M XML -e 'my $start = now; $ = from-xml(slurp("ManagedSystem.xml")); note "parse: " ~ now - $start;'; done
parse: 11.698402811
parse: 12.140521
parse: 13.0865156

LibXML-p6<https://github.com/p6-xml/LibXML-p6>
for ((i=1; i<=3; i++)); do perl6 -M LibXML -e 'my $xml-manager = LibXML.new; my $start = now; $ = $xml-manager.parse(:string(slurp("ManagementConsole.xml"))); note "parse: " ~ now - $start;'; done
parse: 0.0128505
parse: 0.01328376
parse: 0.0123331
for ((i=1; i<=3; i++)); do perl6 -M LibXML -e 'my $xml-manager = LibXML.new; my $start = now; $ = $xml-manager.parse(:string(slurp("ManagedSystem.xml"))); note "parse: " ~ now - $start'; done
parse: 0.1062065
parse: 0.1151403
parse: 0.110503

Awesome!

Thanks for working on this,

Mark

**Comment by dwarring** [comment]
Hi Mark,
100x seems pretty good. I shaved a bit more off, by using the :io($path) parse option.

david@toshiba:~/git/LibXML-p6$ for ((i=1; i<=3; i++)); do perl6 -I . -M LibXML -e 'my $xml-manager = LibXML.new; my $start = now; $ = $xml-manager.parse(:string(slurp("etc/libxml2-api.xml"))); note "parse: " ~ now - $start;'; done
parse: 0.1345104
parse: 0.1358056
parse: 0.1328469
david@toshiba:~/git/LibXML-p6$ for ((i=1; i<=3; i++)); do perl6 -I . -M LibXML -e 'my $xml-manager = LibXML.new; my $start = now; $ = $xml-manager.parse(:io("etc/libxml2-api.xml")); note "parse: " ~ now - $start;'; done
parse: 0.092458
parse: 0.0797928
parse: 0.09454625

This allows the file to be read directly by libxml.
