### ISSUE TITLE
`suppress-errors` and `suppress-warnings` still outputs errors

### ISSUE THREAD

**Issue by leedo** [p6-xml/LibXML-p6#24]
I'm trying to parse an HTML5 string with LibXML::Parser. I'm using the `:recover`, `:suppress-errors`, and `:suppress-warnings` options, and it still seems to output error messages about unknown entities. It does however successfully parse the document.

Here is a test script I am using:

```perl6
#!/usr/bin/env perl6

use v6;
use LibXML;
use Test;

my $html = q:to/HTML/;
<!DOCTYPE html>
<html>
<body>
<aside>hello</aside>
<nav>goodbye</nav>
</body>
</html>
HTML

my $parser = LibXML.new;
my $doc = $parser.parse(
    :string($html),
    :recover,
    :suppress-errors,
    :suppress-warnings,
    :html
);

isa-ok $doc, 'LibXML::Document';
```

And the output is:
```
$ perl6 test.pl 
:4: HTML parser error : Tag aside invalid
:5: HTML parser error : Tag nav invalid
  in block  at /Users/laylward/local/share/perl6/site/sources/46BF5C61FDD7BCC3A6ACF076F9C5EC1ABE6742EC (LibXML::ErrorHandler) line 162
ok 1 - The object is-a '"LibXML::Document"'
```

This is ported from a perl5 script that was using similar options, and did not seem to output such messages.

**Comment by dwarring** [comment]
Problems was that LibXML::ErrorHandler delegate, objects had their own suppress-errors and suppress-warnings flags which weren't being set. Side-stepped the issue by changing it from a deleagte object to a role (renamed to LibXML::ErrorHandling).

**Comment by dwarring** [comment]
@leedo. Can you please retry with LibXML 0.1.6 (uploaded to CPAN).

**Comment by leedo** [comment]
0.1.6 looks to have fixed this for me. Thanks so much for your work on this!
